version: '3'

services:
  
  # Frontend >> docker build ./frontend -t dmw2151/astro_frontend
  frontend:
    image: dmw2151/astro_frontend
    restart: unless-stopped
    ports:
      - "8000:8000"

  # Backend >> docker build . -t dmw2151/tle_tb_astro
  tlepub:
    image: dmw2151/tle_tb_astro
    restart: unless-stopped
    expose: 
      - 5555
    command: |
      python3 ./src/astro_obj_manager_proc.py

  tlesub:
    image: dmw2151/tle_tb_astro
    restart: unless-stopped
    depends_on:
      - tlepub
    links:
      - tlepub
    environment:
      - TB_WORKSPACE_RW_TOKEN=$TB_RW_TOKEN
      - TB_TARGET_ENDPOINT=https://api.tinybird.co/v0/events
      - TB_TARGET_TABLE=astro_obj_positions
      - TLEW_WORKER_CONNECT_ADDR=tlepub
    command: |
      python3 ./src/astro_obj_worker_proc.py
